//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.AppData
{
    using System;
    
    public partial class GetTransSaleList_Result1
    {
        public int SaleHeaderID { get; set; }
        public string CustomerName { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedBy { get; set; }
        public string SaleNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public string SerialNumber { get; set; }
        public string BillType { get; set; }
    }
}
