//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasUserLogin
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    }
}
