//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasValueList
    {
        public string FUNC { get; set; }
        public string TYPES { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISACTIVE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
